version: '3'

tasks:
  mock:
    desc: Generate mocks for interfaces
    cmds:
      - mockery --name=Context --dir=. --output=./mocks --outpkg=mocks
      - mockery --name=Binder --dir=. --output=./mocks --outpkg=mocks
      - mockery --name=ErrorEncoder --dir=. --output=./mocks --outpkg=mocks
      - mockery --name=Route --dir=. --output=./mocks --outpkg=mocks
      - mockery --name=RouteBuilder --dir=. --output=./mocks --outpkg=mocks
      - mockery --name=Group --dir=. --output=./mocks --outpkg=mocks

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test-cover:
    desc: Run tests with coverage and open HTML report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out