version: '3'

tasks:
  mock:
    desc: Generate mocks for the Context interface
    cmds:
      - mockery --name=Context --dir=. --output=./mocks --outpkg=mocks

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test-cover:
    desc: Run tests with coverage and open HTML report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out