// Code generated by go-enum DO NOT EDIT.

package openapi

import (
	"errors"
	"fmt"
)

const (
	// UILibRedoc is a UILib of type redoc.
	UILibRedoc UILib = "redoc"
	// UILibScalar is a UILib of type scalar.
	UILibScalar UILib = "scalar"
)

var ErrInvalidUILib = errors.New("not a valid UILib")

// String implements the Stringer interface.
func (x UILib) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x UILib) IsValid() bool {
	_, err := ParseUILib(string(x))
	return err == nil
}

var _UILibValue = map[string]UILib{
	"redoc":  UILibRedoc,
	"scalar": UILibScalar,
}

// ParseUILib attempts to convert a string to a UILib.
func ParseUILib(name string) (UILib, error) {
	if x, ok := _UILibValue[name]; ok {
		return x, nil
	}
	return UILib(""), fmt.Errorf("%s is %w", name, ErrInvalidUILib)
}
