// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	miniapi "github.com/cirius-go/miniapi"
	mock "github.com/stretchr/testify/mock"
)

// Binder is an autogenerated mock type for the Binder type
type Binder struct {
	mock.Mock
}

// BindRequest provides a mock function with given fields: ctx, req
func (_m *Binder) BindRequest(ctx miniapi.Context, req interface{}) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for BindRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(miniapi.Context, interface{}) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarshalResponse provides a mock function with given fields: ctx, res
func (_m *Binder) MarshalResponse(ctx miniapi.Context, res interface{}) error {
	ret := _m.Called(ctx, res)

	if len(ret) == 0 {
		panic("no return value specified for MarshalResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(miniapi.Context, interface{}) error); ok {
		r0 = rf(ctx, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBinder creates a new instance of Binder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Binder {
	mock := &Binder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
