// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	iter "iter"

	miniapi "github.com/cirius-go/miniapi"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"

	tls "crypto/tls"

	url "net/url"
)

// Context is an autogenerated mock type for the Context type
type Context struct {
	mock.Mock
}

// AppendResponseHeader provides a mock function with given fields: name, value
func (_m *Context) AppendResponseHeader(name string, value string) {
	_m.Called(name, value)
}

// IterRequestHeader provides a mock function with no fields
func (_m *Context) IterRequestHeader() iter.Seq2[string, string] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IterRequestHeader")
	}

	var r0 iter.Seq2[string, string]
	if rf, ok := ret.Get(0).(func() iter.Seq2[string, string]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[string, string])
		}
	}

	return r0
}

// RemoteAddress provides a mock function with no fields
func (_m *Context) RemoteAddress() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteAddress")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RequestBodyReader provides a mock function with no fields
func (_m *Context) RequestBodyReader() io.ReadCloser {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestBodyReader")
	}

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	return r0
}

// RequestContext provides a mock function with no fields
func (_m *Context) RequestContext() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestContext")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// RequestHeader provides a mock function with given fields: name
func (_m *Context) RequestHeader(name string) string {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for RequestHeader")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RequestHost provides a mock function with no fields
func (_m *Context) RequestHost() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestHost")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RequestMethod provides a mock function with no fields
func (_m *Context) RequestMethod() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestMethod")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RequestMultipartForm provides a mock function with given fields: maxMemory
func (_m *Context) RequestMultipartForm(maxMemory int64) (*multipart.Form, error) {
	ret := _m.Called(maxMemory)

	if len(ret) == 0 {
		panic("no return value specified for RequestMultipartForm")
	}

	var r0 *multipart.Form
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*multipart.Form, error)); ok {
		return rf(maxMemory)
	}
	if rf, ok := ret.Get(0).(func(int64) *multipart.Form); ok {
		r0 = rf(maxMemory)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*multipart.Form)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(maxMemory)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestParam provides a mock function with given fields: name
func (_m *Context) RequestParam(name string) string {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for RequestParam")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RequestQuery provides a mock function with given fields: name
func (_m *Context) RequestQuery(name string) string {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for RequestQuery")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RequestTLS provides a mock function with no fields
func (_m *Context) RequestTLS() *tls.ConnectionState {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestTLS")
	}

	var r0 *tls.ConnectionState
	if rf, ok := ret.Get(0).(func() *tls.ConnectionState); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.ConnectionState)
		}
	}

	return r0
}

// RequestURL provides a mock function with no fields
func (_m *Context) RequestURL() url.URL {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestURL")
	}

	var r0 url.URL
	if rf, ok := ret.Get(0).(func() url.URL); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(url.URL)
	}

	return r0
}

// ResponseBodyWriter provides a mock function with no fields
func (_m *Context) ResponseBodyWriter() io.Writer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResponseBodyWriter")
	}

	var r0 io.Writer
	if rf, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}

	return r0
}

// ResponseHeader provides a mock function with given fields: name
func (_m *Context) ResponseHeader(name string) string {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ResponseHeader")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ResponseStatus provides a mock function with no fields
func (_m *Context) ResponseStatus() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResponseStatus")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Route provides a mock function with no fields
func (_m *Context) Route() miniapi.Route {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Route")
	}

	var r0 miniapi.Route
	if rf, ok := ret.Get(0).(func() miniapi.Route); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.Route)
		}
	}

	return r0
}

// SetRequestContext provides a mock function with given fields: ctx
func (_m *Context) SetRequestContext(ctx context.Context) {
	_m.Called(ctx)
}

// SetResponseHeader provides a mock function with given fields: name, value
func (_m *Context) SetResponseHeader(name string, value string) {
	_m.Called(name, value)
}

// SetResponseStatus provides a mock function with given fields: status
func (_m *Context) SetResponseStatus(status int) {
	_m.Called(status)
}

// NewContext creates a new instance of Context. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *Context {
	mock := &Context{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
