// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	miniapi "github.com/cirius-go/miniapi"
	mock "github.com/stretchr/testify/mock"
)

// ErrorEncoder is an autogenerated mock type for the ErrorEncoder type
type ErrorEncoder struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *ErrorEncoder) Execute(_a0 miniapi.Context, _a1 error) {
	_m.Called(_a0, _a1)
}

// NewErrorEncoder creates a new instance of ErrorEncoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorEncoder {
	mock := &ErrorEncoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
