// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	miniapi "github.com/cirius-go/miniapi"
	mock "github.com/stretchr/testify/mock"
)

// Group is an autogenerated mock type for the Group type
type Group struct {
	mock.Mock
}

// AddGroups provides a mock function with given fields: groups
func (_m *Group) AddGroups(groups ...miniapi.Group) miniapi.Group {
	_va := make([]interface{}, len(groups))
	for _i := range groups {
		_va[_i] = groups[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddGroups")
	}

	var r0 miniapi.Group
	if rf, ok := ret.Get(0).(func(...miniapi.Group) miniapi.Group); ok {
		r0 = rf(groups...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.Group)
		}
	}

	return r0
}

// AddMiddlewares provides a mock function with given fields: middlewares
func (_m *Group) AddMiddlewares(middlewares ...miniapi.Middleware) miniapi.Group {
	_va := make([]interface{}, len(middlewares))
	for _i := range middlewares {
		_va[_i] = middlewares[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddMiddlewares")
	}

	var r0 miniapi.Group
	if rf, ok := ret.Get(0).(func(...miniapi.Middleware) miniapi.Group); ok {
		r0 = rf(middlewares...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.Group)
		}
	}

	return r0
}

// AddModifiers provides a mock function with given fields: modifiers
func (_m *Group) AddModifiers(modifiers ...miniapi.Modifier) miniapi.Group {
	_va := make([]interface{}, len(modifiers))
	for _i := range modifiers {
		_va[_i] = modifiers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddModifiers")
	}

	var r0 miniapi.Group
	if rf, ok := ret.Get(0).(func(...miniapi.Modifier) miniapi.Group); ok {
		r0 = rf(modifiers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.Group)
		}
	}

	return r0
}

// AddRoutes provides a mock function with given fields: routes
func (_m *Group) AddRoutes(routes ...miniapi.RouteBuilder) miniapi.Group {
	_va := make([]interface{}, len(routes))
	for _i := range routes {
		_va[_i] = routes[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddRoutes")
	}

	var r0 miniapi.Group
	if rf, ok := ret.Get(0).(func(...miniapi.RouteBuilder) miniapi.Group); ok {
		r0 = rf(routes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.Group)
		}
	}

	return r0
}

// Binder provides a mock function with no fields
func (_m *Group) Binder() miniapi.Binder {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Binder")
	}

	var r0 miniapi.Binder
	if rf, ok := ret.Get(0).(func() miniapi.Binder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.Binder)
		}
	}

	return r0
}

// Build provides a mock function with given fields: _a0
func (_m *Group) Build(_a0 miniapi.BuildContext) []miniapi.Route {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 []miniapi.Route
	if rf, ok := ret.Get(0).(func(miniapi.BuildContext) []miniapi.Route); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]miniapi.Route)
		}
	}

	return r0
}

// ErrorEncoder provides a mock function with no fields
func (_m *Group) ErrorEncoder() miniapi.ErrorEncoder {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ErrorEncoder")
	}

	var r0 miniapi.ErrorEncoder
	if rf, ok := ret.Get(0).(func() miniapi.ErrorEncoder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.ErrorEncoder)
		}
	}

	return r0
}

// Middlewares provides a mock function with no fields
func (_m *Group) Middlewares() []miniapi.Middleware {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Middlewares")
	}

	var r0 []miniapi.Middleware
	if rf, ok := ret.Get(0).(func() []miniapi.Middleware); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]miniapi.Middleware)
		}
	}

	return r0
}

// Modifiers provides a mock function with no fields
func (_m *Group) Modifiers() []miniapi.Modifier {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Modifiers")
	}

	var r0 []miniapi.Modifier
	if rf, ok := ret.Get(0).(func() []miniapi.Modifier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]miniapi.Modifier)
		}
	}

	return r0
}

// NewGroup provides a mock function with given fields: prefix
func (_m *Group) NewGroup(prefix string) miniapi.Group {
	ret := _m.Called(prefix)

	if len(ret) == 0 {
		panic("no return value specified for NewGroup")
	}

	var r0 miniapi.Group
	if rf, ok := ret.Get(0).(func(string) miniapi.Group); ok {
		r0 = rf(prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.Group)
		}
	}

	return r0
}

// Prefix provides a mock function with no fields
func (_m *Group) Prefix() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Prefix")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetBinder provides a mock function with given fields: b
func (_m *Group) SetBinder(b miniapi.Binder) miniapi.Group {
	ret := _m.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for SetBinder")
	}

	var r0 miniapi.Group
	if rf, ok := ret.Get(0).(func(miniapi.Binder) miniapi.Group); ok {
		r0 = rf(b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.Group)
		}
	}

	return r0
}

// SetErrorEncoder provides a mock function with given fields: e
func (_m *Group) SetErrorEncoder(e miniapi.ErrorEncoder) miniapi.Group {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for SetErrorEncoder")
	}

	var r0 miniapi.Group
	if rf, ok := ret.Get(0).(func(miniapi.ErrorEncoder) miniapi.Group); ok {
		r0 = rf(e)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.Group)
		}
	}

	return r0
}

// SetPrefix provides a mock function with given fields: prefix
func (_m *Group) SetPrefix(prefix string) miniapi.Group {
	ret := _m.Called(prefix)

	if len(ret) == 0 {
		panic("no return value specified for SetPrefix")
	}

	var r0 miniapi.Group
	if rf, ok := ret.Get(0).(func(string) miniapi.Group); ok {
		r0 = rf(prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.Group)
		}
	}

	return r0
}

// NewGroup creates a new instance of Group. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroup(t interface {
	mock.TestingT
	Cleanup(func())
}) *Group {
	mock := &Group{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
