// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	miniapi "github.com/cirius-go/miniapi"
	mock "github.com/stretchr/testify/mock"

	reflect "reflect"
)

// RouteBuilder is an autogenerated mock type for the RouteBuilder type
type RouteBuilder struct {
	mock.Mock
}

// AddMiddlewares provides a mock function with given fields: middlewares
func (_m *RouteBuilder) AddMiddlewares(middlewares ...miniapi.Middleware) miniapi.RouteBuilder {
	_va := make([]interface{}, len(middlewares))
	for _i := range middlewares {
		_va[_i] = middlewares[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddMiddlewares")
	}

	var r0 miniapi.RouteBuilder
	if rf, ok := ret.Get(0).(func(...miniapi.Middleware) miniapi.RouteBuilder); ok {
		r0 = rf(middlewares...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.RouteBuilder)
		}
	}

	return r0
}

// AddModifiers provides a mock function with given fields: modifiers
func (_m *RouteBuilder) AddModifiers(modifiers ...miniapi.Modifier) miniapi.RouteBuilder {
	_va := make([]interface{}, len(modifiers))
	for _i := range modifiers {
		_va[_i] = modifiers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddModifiers")
	}

	var r0 miniapi.RouteBuilder
	if rf, ok := ret.Get(0).(func(...miniapi.Modifier) miniapi.RouteBuilder); ok {
		r0 = rf(modifiers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.RouteBuilder)
		}
	}

	return r0
}

// Binder provides a mock function with no fields
func (_m *RouteBuilder) Binder() miniapi.Binder {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Binder")
	}

	var r0 miniapi.Binder
	if rf, ok := ret.Get(0).(func() miniapi.Binder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.Binder)
		}
	}

	return r0
}

// Build provides a mock function with given fields: ctx
func (_m *RouteBuilder) Build(ctx miniapi.BuildContext) miniapi.Route {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 miniapi.Route
	if rf, ok := ret.Get(0).(func(miniapi.BuildContext) miniapi.Route); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.Route)
		}
	}

	return r0
}

// ErrorEncoder provides a mock function with no fields
func (_m *RouteBuilder) ErrorEncoder() miniapi.ErrorEncoder {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ErrorEncoder")
	}

	var r0 miniapi.ErrorEncoder
	if rf, ok := ret.Get(0).(func() miniapi.ErrorEncoder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.ErrorEncoder)
		}
	}

	return r0
}

// HandlerFuncBuilder provides a mock function with no fields
func (_m *RouteBuilder) HandlerFuncBuilder() miniapi.HandlerFuncBuilder {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HandlerFuncBuilder")
	}

	var r0 miniapi.HandlerFuncBuilder
	if rf, ok := ret.Get(0).(func() miniapi.HandlerFuncBuilder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.HandlerFuncBuilder)
		}
	}

	return r0
}

// Method provides a mock function with no fields
func (_m *RouteBuilder) Method() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Method")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Middlewares provides a mock function with no fields
func (_m *RouteBuilder) Middlewares() []miniapi.Middleware {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Middlewares")
	}

	var r0 []miniapi.Middleware
	if rf, ok := ret.Get(0).(func() []miniapi.Middleware); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]miniapi.Middleware)
		}
	}

	return r0
}

// Modifiers provides a mock function with no fields
func (_m *RouteBuilder) Modifiers() []miniapi.Modifier {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Modifiers")
	}

	var r0 []miniapi.Modifier
	if rf, ok := ret.Get(0).(func() []miniapi.Modifier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]miniapi.Modifier)
		}
	}

	return r0
}

// Operation provides a mock function with no fields
func (_m *RouteBuilder) Operation() miniapi.Operation {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operation")
	}

	var r0 miniapi.Operation
	if rf, ok := ret.Get(0).(func() miniapi.Operation); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(miniapi.Operation)
	}

	return r0
}

// Path provides a mock function with no fields
func (_m *RouteBuilder) Path() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ReqType provides a mock function with no fields
func (_m *RouteBuilder) ReqType() reflect.Type {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReqType")
	}

	var r0 reflect.Type
	if rf, ok := ret.Get(0).(func() reflect.Type); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.Type)
		}
	}

	return r0
}

// ResType provides a mock function with no fields
func (_m *RouteBuilder) ResType() reflect.Type {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResType")
	}

	var r0 reflect.Type
	if rf, ok := ret.Get(0).(func() reflect.Type); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.Type)
		}
	}

	return r0
}

// SetBinder provides a mock function with given fields: b
func (_m *RouteBuilder) SetBinder(b miniapi.Binder) miniapi.RouteBuilder {
	ret := _m.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for SetBinder")
	}

	var r0 miniapi.RouteBuilder
	if rf, ok := ret.Get(0).(func(miniapi.Binder) miniapi.RouteBuilder); ok {
		r0 = rf(b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.RouteBuilder)
		}
	}

	return r0
}

// SetErrorEncoder provides a mock function with given fields: e
func (_m *RouteBuilder) SetErrorEncoder(e miniapi.ErrorEncoder) miniapi.RouteBuilder {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for SetErrorEncoder")
	}

	var r0 miniapi.RouteBuilder
	if rf, ok := ret.Get(0).(func(miniapi.ErrorEncoder) miniapi.RouteBuilder); ok {
		r0 = rf(e)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.RouteBuilder)
		}
	}

	return r0
}

// SetMethod provides a mock function with given fields: method
func (_m *RouteBuilder) SetMethod(method string) miniapi.RouteBuilder {
	ret := _m.Called(method)

	if len(ret) == 0 {
		panic("no return value specified for SetMethod")
	}

	var r0 miniapi.RouteBuilder
	if rf, ok := ret.Get(0).(func(string) miniapi.RouteBuilder); ok {
		r0 = rf(method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.RouteBuilder)
		}
	}

	return r0
}

// SetOperation provides a mock function with given fields: op
func (_m *RouteBuilder) SetOperation(op miniapi.Operation) miniapi.RouteBuilder {
	ret := _m.Called(op)

	if len(ret) == 0 {
		panic("no return value specified for SetOperation")
	}

	var r0 miniapi.RouteBuilder
	if rf, ok := ret.Get(0).(func(miniapi.Operation) miniapi.RouteBuilder); ok {
		r0 = rf(op)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.RouteBuilder)
		}
	}

	return r0
}

// SetPath provides a mock function with given fields: path
func (_m *RouteBuilder) SetPath(path string) miniapi.RouteBuilder {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for SetPath")
	}

	var r0 miniapi.RouteBuilder
	if rf, ok := ret.Get(0).(func(string) miniapi.RouteBuilder); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.RouteBuilder)
		}
	}

	return r0
}

// NewRouteBuilder creates a new instance of RouteBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRouteBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *RouteBuilder {
	mock := &RouteBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
