// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	miniapi "github.com/cirius-go/miniapi"
	mock "github.com/stretchr/testify/mock"
)

// Route is an autogenerated mock type for the Route type
type Route struct {
	mock.Mock
}

// HandlerFunc provides a mock function with no fields
func (_m *Route) HandlerFunc() miniapi.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HandlerFunc")
	}

	var r0 miniapi.HandlerFunc
	if rf, ok := ret.Get(0).(func() miniapi.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(miniapi.HandlerFunc)
		}
	}

	return r0
}

// Method provides a mock function with no fields
func (_m *Route) Method() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Method")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Operation provides a mock function with no fields
func (_m *Route) Operation() miniapi.Operation {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operation")
	}

	var r0 miniapi.Operation
	if rf, ok := ret.Get(0).(func() miniapi.Operation); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(miniapi.Operation)
	}

	return r0
}

// Path provides a mock function with no fields
func (_m *Route) Path() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewRoute creates a new instance of Route. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoute(t interface {
	mock.TestingT
	Cleanup(func())
}) *Route {
	mock := &Route{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
